#pragma once

/**
 * @file Zobrist.h
 * @brief Deterministic Zobrist hashing for chess positions.
 */

#include "chess/Position.h"

#include <cstdint>

namespace cnnv::chess {

/**
 * @brief Computes a deterministic Zobrist-style hash from scratch.
 * @param pos Position to hash.
 * @return 64-bit hash including pieces, side-to-move, castling, and en-passant.
 *
 * Keys are generated by a fixed-seed SplitMix64 PRNG, so identical positions
 * hash identically across runs. Complexity is O(64), which is sufficient for
 * visualizer use.
 */
std::uint64_t computeZobristHash(const Position& pos) noexcept;

}  // namespace cnnv::chess
